default: &default
  region: "us-east1"
  zone: "us-east1-a"
  gcp:
    project: "hc-public"
    service_account: "~/safe/hc-public/terraform.json"
    bucket_name: "kite-state-helios-devel"
# aws:
#   access_key: "********************"
#   secret_key: "****************************************"
#   vpc_cidr_block: "10.0.0.0/16"
dev:
  <<: *default
  gcp:
    project: "helios-devel"
    service_account: "~/safe/helios-devel.json"
    bucket_name: "kite-state-helios-devel"
